### ISSUE TITLE
Main chat room: Discuss about the project

### ISSUE THREAD

**Issue by OBlount** [OBlount/magikarp-bot#1]
### Welcome to the main discussion thread:

**Comment by OBlount** [comment]
Just a thought about how to add players to the game. Would we want to add everyone who is on the server (and anyone who joins the server) to the database?

Or is it an idea for the bot to ask if the user wants to join the game, and then for example, add them to the db if they react to the message.

**Comment by Thetvdh** [comment]
> Just a thought about how to add players to the game. Would we want to add everyone who is on the server (and anyone who joins the server) to the database?
> 
> Or is it an idea for the bot to ask if the user wants to join the game, and then for example, add them to the db if they react to the message.

Second option would keep db size down which could be important when the db gets bigger with the mons added etc

**Comment by OBlount** [comment]
Quick question: Are we keeping `database_manager.py`? (Correct me if I'm wrong but it is never used anymore once async is up and running)

We can flag it as deprecated. No harm in keeping it. It's decent code. Up to you.

**Comment by Thetvdh** [comment]
> 

I added to to the .gitignore with the purpose of leaving it as some reference incase I missed anything. We can take it off the repo and just leave it on our local branches.

**Comment by Thetvdh** [comment]
Discord has changed a lot. Maybe it's time to kill it...

**Comment by OBlount** [comment]
The project hasn't had any work done for a year. Time to retire the repo.
The idea is there though. Maybe one day, we'll come back to making it. Who knows.
